apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  replicas: 1
  template:
    metadata:
      name: wordpress
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: service-wordpress
          imagePullPolicy: Never
          ports:
            - containerPort: 5050
          volumeMounts:
            - name: wordpress-config
              mountPath: /var/www/wordpress/conf_dir
              readOnly: false
      volumes:
        - name: wordpress-config
          configMap:
            name: wordpress-config
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    app: wordpress
  type: LoadBalancer
  ports:
  - port: 5050
    name: wordpress
    targetPort: 5050
