apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  replicas: 1
  template:
    metadata:
      name: phpmyadmin
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: service-phpmyadmin
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: phpmyadmin
#   labels:
#     app: phpmyadmin
# spec:
#   selector:
#     app: phpmyadmin
#   ports:
#     - port: 5000
#       name: phpmyadmin
#       targetPort: 5000
